/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppAlert: typeof import('./src/components/app/AppAlert.vue')['default']
    AppCard: typeof import('./src/components/app/AppCard.vue')['default']
    AppGrid: typeof import('./src/components/app/AppGrid.vue')['default']
    AppModal: typeof import('./src/components/app/AppModal.vue')['default']
    AppPagenation: typeof import('./src/components/app/AppPagenation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
